# Generated by Django 2.2.3 on 2020-03-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherSTUFF', '0002_changedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeDetails',
        ),
    ]
