# Generated by Django 2.2.3 on 2020-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherSTUFF', '0003_delete_changedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
