# Generated by Django 2.2.3 on 2020-03-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherSTUFF', '0004_pin_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_places',
        ),
        migrations.CreateModel(
            name='FavouritePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('x_val', models.FloatField()),
                ('y_val', models.FloatField()),
                ('slug', models.SlugField()),
                ('users', models.ManyToManyField(to='WeatherSTUFF.UserProfile')),
            ],
        ),
    ]
