# Generated by Django 2.2.3 on 2020-03-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherSTUFF', '0005_auto_20200324_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteplace',
            name='users',
        ),
        migrations.AddField(
            model_name='favouriteplace',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WeatherSTUFF.UserProfile'),
            preserve_default=False,
        ),
    ]
